# -*- coding: utf-8 -*-
"""deep learning 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxUZ4wWEhaOwc6Em_T9FHo8FKBVmGGSw
"""

import cv2
from moviepy.editor import VideoFileClip
from google.colab.patches import cv2_imshow

# Read image
img = cv2.imread("images.jpg")
print("Original Image:")
cv2_imshow(img)

# BW
bw = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print("Black and White Image:")
cv2_imshow(bw)

# Properties
h, w, c = img.shape
print(f"Image Properties: Height={h}, Width={w}, Channels={c}")

# Rotations
r90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
print("Rotated 90 degrees clockwise:")
cv2_imshow(r90)

r180 = cv2.rotate(img, cv2.ROTATE_180)
print("Rotated 180 degrees:")
cv2_imshow(r180)

r270 = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
print("Rotated 270 degrees / 90 degrees anti-clockwise:")
cv2_imshow(r270)

# Mirror
mirror = cv2.flip(img, 1) # 1 for horizontal flip, 0 for vertical, -1 for both
print("Mirror Image (Horizontal Flip):")
cv2_imshow(mirror)

# Object detection (no ML)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
_, th = cv2.threshold(gray, 120, 255, cv2.THRESH_BINARY)
# Find contours
cts, _ = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
print(f"Objects detected without Deep Learning: {len(cts)}")

# Vertical 50-50
left = img[:, :w//2]
right = img[:, w//2:]
print("Vertical 50-50 cut (Left and Right parts):")
cv2_imshow(left)
cv2_imshow(right)

# Horizontal 50-50
top = img[:h//2, :]
bottom = img[h//2:, :]
print("Horizontal 50-50 cut (Top and Bottom parts):")
cv2_imshow(top)
cv2_imshow(bottom)

# Vertical 70-30
cut_w_70 = int(w * 0.7)
v_p70 = img[:, :cut_w_70] # 70% of width
v_p30 = img[:, cut_w_70:] # Remaining 30% of width
print("Vertical 70-30 cut (70% and 30% width parts):")
cv2_imshow(v_p70)
cv2_imshow(v_p30)

# Horizontal 70-30
cut_h_70 = int(h * 0.7)
h_p70 = img[:cut_h_70, :] # 70% of height
h_p30 = img[cut_h_70:, :] # Remaining 30% of height
print("Horizontal 70-30 cut (70% and 30% height parts):")
cv2_imshow(h_p70)
cv2_imshow(h_p30)

# Make small grids (2x5 example)
gh = h // 2
gw = w // 5
grids = []
for i in range(2):
    for j in range(5):
        grids.append(img[i*gh:(i+1)*gh, j*gw:(j+1)*gw])

print("Sample Grids (first 3):")
if len(grids) > 0:
    cv2_imshow(grids[0])
if len(grids) > 1:
    cv2_imshow(grids[1])
if len(grids) > 2:
    cv2_imshow(grids[2])