# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJ4JNbvSXJuubu4tpPLSFv2IL3Y8WRaU
"""

import streamlit as st
import cv2
import numpy as np
from PIL import Image


def main():
    st.set_page_config(page_title="Deep Learning Image Basics", layout="wide")

    st.title("Image Processing & Augmentation App")
    st.markdown("Based on OpenCV basics: Rotations, Thresholding, Slicing, and Gridding.")

    # Sidebar for Upload
    st.sidebar.header("Upload Image")
    uploaded_file = st.sidebar.file_uploader("Choose an image...", type=['jpg', 'jpeg', 'png'])

    if uploaded_file is not None:
        # Convert the file to an opencv image.
        file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
        img = cv2.imdecode(file_bytes, 1)

        # Get Dimensions
        h, w, c = img.shape

        # Sidebar Stats
        st.sidebar.markdown("### Image Properties")
        st.sidebar.write(f"**Height:** {h} px")
        st.sidebar.write(f"**Width:** {w} px")
        st.sidebar.write(f"**Channels:** {c}")

        # Create Tabs for different operations
        tab1, tab2, tab3, tab4, tab5 = st.tabs([
            "Original & BW",
            "Rotations & Mirror",
            "Object Detection",
            "Slicing (Cuts)",
            "Grids"
        ])

        # --- TAB 1: Original & BW ---
        with tab1:
            col1, col2 = st.columns(2)

            with col1:
                st.subheader("Original Image")
                # Convert BGR to RGB for Streamlit display
                st.image(cv2.cvtColor(img, cv2.COLOR_BGR2RGB), use_column_width=True)

            with col2:
                st.subheader("Black & White (Grayscale)")
                bw = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
                st.image(bw, use_column_width=True, channels="GRAY")

        # --- TAB 2: Rotations ---
        with tab2:
            st.subheader("Rotations & Flips")

            col_r1, col_r2, col_r3 = st.columns(3)

            with col_r1:
                st.caption("90° Clockwise")
                r90 = cv2.rotate(img, cv2.ROTATE_90_CLOCKWISE)
                st.image(cv2.cvtColor(r90, cv2.COLOR_BGR2RGB), use_column_width=True)

            with col_r2:
                st.caption("180° Rotation")
                r180 = cv2.rotate(img, cv2.ROTATE_180)
                st.image(cv2.cvtColor(r180, cv2.COLOR_BGR2RGB), use_column_width=True)

            with col_r3:
                st.caption("270° (90° Counter-Clockwise)")
                r270 = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
                st.image(cv2.cvtColor(r270, cv2.COLOR_BGR2RGB), use_column_width=True)

            st.divider()
            st.subheader("Mirroring")
            mirror = cv2.flip(img, 1) # 1 for horizontal
            st.image(cv2.cvtColor(mirror, cv2.COLOR_BGR2RGB), caption="Horizontal Flip", width=400)

        # --- TAB 3: Detection ---
        with tab3:
            st.subheader("Simple Object Detection (Contours)")

            # Threshold slider
            thresh_val = st.slider("Threshold Value", 0, 255, 120)

            gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
            _, th = cv2.threshold(gray, thresh_val, 255, cv2.THRESH_BINARY)

            # Find contours
            cts, _ = cv2.findContours(th, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

            # Visualize contours on a copy of the image
            img_contours = img.copy()
            cv2.drawContours(img_contours, cts, -1, (0, 255, 0), 2)

            st.write(f"**Objects detected:** {len(cts)}")

            c1, c2 = st.columns(2)
            with c1:
                st.image(th, caption="Binary Map", use_column_width=True)
            with c2:
                st.image(cv2.cvtColor(img_contours, cv2.COLOR_BGR2RGB), caption="Contours Drawn", use_column_width=True)

        # --- TAB 4: Slicing ---
        with tab4:
            st.subheader("Image Slicing")

            slice_type = st.selectbox("Select Slice Type",
                                      ["Vertical 50-50", "Horizontal 50-50", "Vertical 70-30", "Horizontal 70-30"])

            col_a, col_b = st.columns(2)

            if slice_type == "Vertical 50-50":
                left = img[:, :w//2]
                right = img[:, w//2:]
                col_a.image(cv2.cvtColor(left, cv2.COLOR_BGR2RGB), caption="Left Part", use_column_width=True)
                col_b.image(cv2.cvtColor(right, cv2.COLOR_BGR2RGB), caption="Right Part", use_column_width=True)

            elif slice_type == "Horizontal 50-50":
                top = img[:h//2, :]
                bottom = img[h//2:, :]
                col_a.image(cv2.cvtColor(top, cv2.COLOR_BGR2RGB), caption="Top Part", use_column_width=True)
                col_b.image(cv2.cvtColor(bottom, cv2.COLOR_BGR2RGB), caption="Bottom Part", use_column_width=True)

            elif slice_type == "Vertical 70-30":
                cut_w_70 = int(w * 0.7)
                v_p70 = img[:, :cut_w_70]
                v_p30 = img[:, cut_w_70:]
                col_a.image(cv2.cvtColor(v_p70, cv2.COLOR_BGR2RGB), caption="70% Width", use_column_width=True)
                col_b.image(cv2.cvtColor(v_p30, cv2.COLOR_BGR2RGB), caption="30% Width", use_column_width=True)

            elif slice_type == "Horizontal 70-30":
                cut_h_70 = int(h * 0.7)
                h_p70 = img[:cut_h_70, :]
                h_p30 = img[cut_h_70:, :]
                col_a.image(cv2.cvtColor(h_p70, cv2.COLOR_BGR2RGB), caption="70% Height", use_column_width=True)
                col_b.image(cv2.cvtColor(h_p30, cv2.COLOR_BGR2RGB), caption="30% Height", use_column_width=True)

        # --- TAB 5: Grids ---
        with tab5:
            st.subheader("Grid Split (2 Rows x 5 Columns)")

            gh = h // 2
            gw = w // 5

            # Loop through rows
            for i in range(2):
                cols = st.columns(5)
                for j in range(5):
                    # Crop the grid
                    grid_img = img[i*gh:(i+1)*gh, j*gw:(j+1)*gw]

                    # Display in the specific column
                    with cols[j]:
                        st.image(cv2.cvtColor(grid_img, cv2.COLOR_BGR2RGB), caption=f"Grid {i},{j}")

    else:
        st.info("Please upload an image in the sidebar to begin.")

if __name__ == "__main__":
    main()